
import { ElementData, ElementCategory } from './types.ts';

export const CATEGORY_COLORS: Record<ElementCategory, string> = {
  [ElementCategory.ALKALI_METAL]: 'bg-emerald-600',
  [ElementCategory.ALKALINE_EARTH]: 'bg-rose-600',
  [ElementCategory.TRANSITION_METAL]: 'bg-sky-600',
  [ElementCategory.POST_TRANSITION_METAL]: 'bg-amber-600',
  [ElementCategory.METALLOID]: 'bg-orange-500',
  [ElementCategory.NONMETAL]: 'bg-gray-500',
  [ElementCategory.HALOGEN]: 'bg-purple-600',
  [ElementCategory.NOBLE_GAS]: 'bg-cyan-500',
  [ElementCategory.LANTHANIDE]: 'bg-indigo-500',
  [ElementCategory.ACTINIDE]: 'bg-violet-600',
};

export const CATEGORY_NAMES_FA: Record<ElementCategory, string> = {
  [ElementCategory.ALKALI_METAL]: 'فلزات قلیایی',
  [ElementCategory.ALKALINE_EARTH]: 'فلزات قلیایی خاکی',
  [ElementCategory.TRANSITION_METAL]: 'فلزات واسطه',
  [ElementCategory.POST_TRANSITION_METAL]: 'فلزات پس‌واسطه',
  [ElementCategory.METALLOID]: 'شبه‌فلزات',
  [ElementCategory.NONMETAL]: 'نافلزات',
  [ElementCategory.HALOGEN]: 'هالوژن‌ها',
  [ElementCategory.NOBLE_GAS]: 'گازهای نجیب',
  [ElementCategory.LANTHANIDE]: 'لانتانیدها',
  [ElementCategory.ACTINIDE]: 'اکتینیدها',
};

export const ELEMENTS: ElementData[] = [
  { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', persianName: 'هیدروژن', category: ElementCategory.NONMETAL, electronConfig: '1s¹', group: 1, period: 1, atomicMass: 1.008 },
  { atomicNumber: 2, symbol: 'He', name: 'Helium', persianName: 'هلیم', category: ElementCategory.NOBLE_GAS, electronConfig: '1s²', group: 18, period: 1, atomicMass: 4.0026 },
  { atomicNumber: 3, symbol: 'Li', name: 'Lithium', persianName: 'لیتیم', category: ElementCategory.ALKALI_METAL, electronConfig: '[He] 2s¹', group: 1, period: 2, atomicMass: 6.94 },
  { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', persianName: 'بریلیم', category: ElementCategory.ALKALINE_EARTH, electronConfig: '[He] 2s²', group: 2, period: 2, atomicMass: 9.0122 },
  { atomicNumber: 5, symbol: 'B', name: 'Boron', persianName: 'بور', category: ElementCategory.METALLOID, electronConfig: '[He] 2s² 2p¹', group: 13, period: 2, atomicMass: 10.81 },
  { atomicNumber: 6, symbol: 'C', name: 'Carbon', persianName: 'کربن', category: ElementCategory.NONMETAL, electronConfig: '[He] 2s² 2p²', group: 14, period: 2, atomicMass: 12.011 },
  { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', persianName: 'نیتروژن', category: ElementCategory.NONMETAL, electronConfig: '[He] 2s² 2p³', group: 15, period: 2, atomicMass: 14.007 },
  { atomicNumber: 8, symbol: 'O', name: 'Oxygen', persianName: 'اکسیژن', category: ElementCategory.NONMETAL, electronConfig: '[He] 2s² 2p⁴', group: 16, period: 2, atomicMass: 15.999 },
  { atomicNumber: 9, symbol: 'F', name: 'Fluorine', persianName: 'فلوئور', category: ElementCategory.HALOGEN, electronConfig: '[He] 2s² 2p⁵', group: 17, period: 2, atomicMass: 18.998 },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon', persianName: 'نئون', category: ElementCategory.NOBLE_GAS, electronConfig: '[He] 2s² 2p⁶', group: 18, period: 2, atomicMass: 20.180 },
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium', persianName: 'سدیم', category: ElementCategory.ALKALI_METAL, electronConfig: '[Ne] 3s¹', group: 1, period: 3, atomicMass: 22.990 },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', persianName: 'منیزیم', category: ElementCategory.ALKALINE_EARTH, electronConfig: '[Ne] 3s²', group: 2, period: 3, atomicMass: 24.305 },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminium', persianName: 'آلومینیم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Ne] 3s² 3p¹', group: 13, period: 3, atomicMass: 26.982 },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon', persianName: 'سیلیسیم', category: ElementCategory.METALLOID, electronConfig: '[Ne] 3s² 3p²', group: 14, period: 3, atomicMass: 28.085 },
  { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', persianName: 'فسفر', category: ElementCategory.NONMETAL, electronConfig: '[Ne] 3s² 3p³', group: 15, period: 3, atomicMass: 30.974 },
  { atomicNumber: 16, symbol: 'S', name: 'Sulfur', persianName: 'گوگرد', category: ElementCategory.NONMETAL, electronConfig: '[Ne] 3s² 3p⁴', group: 16, period: 3, atomicMass: 32.06 },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', persianName: 'کلر', category: ElementCategory.HALOGEN, electronConfig: '[Ne] 3s² 3p⁵', group: 17, period: 3, atomicMass: 35.45 },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon', persianName: 'آرگون', category: ElementCategory.NOBLE_GAS, electronConfig: '[Ne] 3s² 3p⁶', group: 18, period: 3, atomicMass: 39.948 },
  { atomicNumber: 19, symbol: 'K', name: 'Potassium', persianName: 'پتاسیم', category: ElementCategory.ALKALI_METAL, electronConfig: '[Ar] 4s¹', group: 1, period: 4, atomicMass: 39.098 },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', persianName: 'کلسیم', category: ElementCategory.ALKALINE_EARTH, electronConfig: '[Ar] 4s²', group: 2, period: 4, atomicMass: 40.078 },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', persianName: 'اسکاندیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d¹ 4s²', group: 3, period: 4, atomicMass: 44.956 },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', persianName: 'تیتانیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d² 4s²', group: 4, period: 4, atomicMass: 47.867 },
  { atomicNumber: 23, symbol: 'V', name: 'Vanadium', persianName: 'وانادیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d³ 4s²', group: 5, period: 4, atomicMass: 50.942 },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', persianName: 'کروم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d⁵ 4s¹', group: 6, period: 4, atomicMass: 51.996 },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', persianName: 'منگنز', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d⁵ 4s²', group: 7, period: 4, atomicMass: 54.938 },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron', persianName: 'آهن', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d⁶ 4s²', group: 8, period: 4, atomicMass: 55.845 },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', persianName: 'کبالت', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d⁷ 4s²', group: 9, period: 4, atomicMass: 58.933 },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', persianName: 'نیکل', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d⁸ 4s²', group: 10, period: 4, atomicMass: 58.693 },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper', persianName: 'مس', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d¹⁰ 4s¹', group: 11, period: 4, atomicMass: 63.546 },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', persianName: 'روی', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Ar] 3d¹⁰ 4s²', group: 12, period: 4, atomicMass: 65.38 },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', persianName: 'گالیم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', group: 13, period: 4, atomicMass: 69.723 },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', persianName: 'ژرمانیم', category: ElementCategory.METALLOID, electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', group: 14, period: 4, atomicMass: 72.630 },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic', persianName: 'آرسنیک', category: ElementCategory.METALLOID, electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', group: 15, period: 4, atomicMass: 74.922 },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium', persianName: 'سلنیم', category: ElementCategory.NONMETAL, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', group: 16, period: 4, atomicMass: 78.971 },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine', persianName: 'بروم', category: ElementCategory.HALOGEN, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', group: 17, period: 4, atomicMass: 79.904 },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', persianName: 'کریپتون', category: ElementCategory.NOBLE_GAS, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', group: 18, period: 4, atomicMass: 83.798 },
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', persianName: 'روبیدیم', category: ElementCategory.ALKALI_METAL, electronConfig: '[Kr] 5s¹', group: 1, period: 5, atomicMass: 85.468 },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', persianName: 'استرانسیم', category: ElementCategory.ALKALINE_EARTH, electronConfig: '[Kr] 5s²', group: 2, period: 5, atomicMass: 87.62 },
  { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', persianName: 'ایتریم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d¹ 5s²', group: 3, period: 5, atomicMass: 88.906 },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', persianName: 'زیرکونیوم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d² 5s²', group: 4, period: 5, atomicMass: 91.224 },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', persianName: 'نیوبیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d⁴ 5s¹', group: 5, period: 5, atomicMass: 92.906 },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', persianName: 'مولیبدن', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d⁵ 5s¹', group: 6, period: 5, atomicMass: 95.95 },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', persianName: 'تکنسیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d⁵ 5s²', group: 7, period: 5, atomicMass: 98 },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', persianName: 'روتنیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d⁷ 5s¹', group: 8, period: 5, atomicMass: 101.07 },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', persianName: 'رودیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d⁸ 5s¹', group: 9, period: 5, atomicMass: 102.91 },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', persianName: 'پالادیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d¹⁰', group: 10, period: 5, atomicMass: 106.42 },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver', persianName: 'نقره', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d¹⁰ 5s¹', group: 11, period: 5, atomicMass: 107.87 },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', persianName: 'کادمیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Kr] 4d¹⁰ 5s²', group: 12, period: 5, atomicMass: 112.41 },
  { atomicNumber: 49, symbol: 'In', name: 'Indium', persianName: 'ایندیم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', group: 13, period: 5, atomicMass: 114.82 },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin', persianName: 'قلع', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', group: 14, period: 5, atomicMass: 118.71 },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony', persianName: 'آنتیموان', category: ElementCategory.METALLOID, electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', group: 15, period: 5, atomicMass: 121.76 },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium', persianName: 'تلوریم', category: ElementCategory.METALLOID, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', group: 16, period: 5, atomicMass: 127.60 },
  { atomicNumber: 53, symbol: 'I', name: 'Iodine', persianName: 'ید', category: ElementCategory.HALOGEN, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', group: 17, period: 5, atomicMass: 126.90 },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon', persianName: 'زنون', category: ElementCategory.NOBLE_GAS, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', group: 18, period: 5, atomicMass: 131.29 },
  { atomicNumber: 55, symbol: 'Cs', name: 'Caesium', persianName: 'سزیم', category: ElementCategory.ALKALI_METAL, electronConfig: '[Xe] 6s¹', group: 1, period: 6, atomicMass: 132.91 },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium', persianName: 'باریم', category: ElementCategory.ALKALINE_EARTH, electronConfig: '[Xe] 6s²', group: 2, period: 6, atomicMass: 137.33 },
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum', persianName: 'لانتان', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 5d¹ 6s²', group: 3, period: 6, atomicMass: 138.91 },
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium', persianName: 'سریم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹ 5d¹ 6s²', group: 4, period: 6, atomicMass: 140.12 },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', persianName: 'پرازئودیمیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f³ 6s²', group: 5, period: 6, atomicMass: 140.91 },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', persianName: 'نئودیمیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f⁴ 6s²', group: 6, period: 6, atomicMass: 144.24 },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium', persianName: 'پرومتیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f⁵ 6s²', group: 7, period: 6, atomicMass: 145 },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium', persianName: 'ساماریم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f⁶ 6s²', group: 8, period: 6, atomicMass: 150.36 },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium', persianName: 'اروپیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f⁷ 6s²', group: 9, period: 6, atomicMass: 151.96 },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', persianName: 'گادولینیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', group: 10, period: 6, atomicMass: 157.25 },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium', persianName: 'تربیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f⁹ 6s²', group: 11, period: 6, atomicMass: 158.93 },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', persianName: 'دیسپروزیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹⁰ 6s²', group: 12, period: 6, atomicMass: 162.50 },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium', persianName: 'هولمیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹¹ 6s²', group: 13, period: 6, atomicMass: 164.93 },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium', persianName: 'اربیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹² 6s²', group: 14, period: 6, atomicMass: 167.26 },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium', persianName: 'تولیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹³ 6s²', group: 15, period: 6, atomicMass: 168.93 },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', persianName: 'ایتربیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹⁴ 6s²', group: 16, period: 6, atomicMass: 173.05 },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', persianName: 'لوتتیم', category: ElementCategory.LANTHANIDE, electronConfig: '[Xe] 4f¹¹ 5d¹ 6s²', group: 17, period: 6, atomicMass: 174.97 },
  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', persianName: 'هافنیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', group: 4, period: 6, atomicMass: 178.49 },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', persianName: 'تانتال', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', group: 5, period: 6, atomicMass: 180.95 },
  { atomicNumber: 74, symbol: 'W', name: 'Tungsten', persianName: 'تنگستن', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', group: 6, period: 6, atomicMass: 183.84 },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium', persianName: 'رنیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', group: 7, period: 6, atomicMass: 186.21 },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium', persianName: 'اسمیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', group: 8, period: 6, atomicMass: 190.23 },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium', persianName: 'ایریدیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', group: 9, period: 6, atomicMass: 192.22 },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum', persianName: 'پلاتین', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', group: 10, period: 6, atomicMass: 195.08 },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold', persianName: 'طلا', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', group: 11, period: 6, atomicMass: 196.97 },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury', persianName: 'جیوه', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', group: 12, period: 6, atomicMass: 200.59 },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium', persianName: 'تالیم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', group: 13, period: 6, atomicMass: 204.38 },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead', persianName: 'سرب', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', group: 14, period: 6, atomicMass: 207.2 },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', persianName: 'بیسموت', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', group: 15, period: 6, atomicMass: 208.98 },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium', persianName: 'پولونیم', category: ElementCategory.METALLOID, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', group: 16, period: 6, atomicMass: 209 },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine', persianName: 'استاتین', category: ElementCategory.METALLOID, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', group: 17, period: 6, atomicMass: 210 },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon', persianName: 'رادون', category: ElementCategory.NOBLE_GAS, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', group: 18, period: 6, atomicMass: 222 },
  { atomicNumber: 87, symbol: 'Fr', name: 'Francium', persianName: 'فرانسیم', category: ElementCategory.ALKALI_METAL, electronConfig: '[Rn] 7s¹', group: 1, period: 7, atomicMass: 223 },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium', persianName: 'رادیم', category: ElementCategory.ALKALINE_EARTH, electronConfig: '[Rn] 7s²', group: 2, period: 7, atomicMass: 226 },
  { atomicNumber: 89, symbol: 'Ac', name: 'Actinium', persianName: 'اکتینیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 6d¹ 7s²', group: 3, period: 7, atomicMass: 227 },
  { atomicNumber: 90, symbol: 'Th', name: 'Thorium', persianName: 'توریم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 6d² 7s²', group: 4, period: 7, atomicMass: 232.04 },
  { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', persianName: 'پروتاکتینیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f² 6d¹ 7s²', group: 5, period: 7, atomicMass: 231.04 },
  { atomicNumber: 92, symbol: 'U', name: 'Uranium', persianName: 'اورانیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f³ 6d¹ 7s²', group: 6, period: 7, atomicMass: 238.03 },
  { atomicNumber: 93, symbol: 'Np', name: 'Neptunium', persianName: 'نپتونیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', group: 7, period: 7, atomicMass: 237 },
  { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', persianName: 'پلوتونیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f⁶ 7s²', group: 8, period: 7, atomicMass: 244 },
  { atomicNumber: 95, symbol: 'Am', name: 'Americium', persianName: 'امریسیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f⁷ 7s²', group: 9, period: 7, atomicMass: 243 },
  { atomicNumber: 96, symbol: 'Cm', name: 'Curium', persianName: 'کوریم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', group: 10, period: 7, atomicMass: 247 },
  { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', persianName: 'برکلیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f⁹ 7s²', group: 11, period: 7, atomicMass: 247 },
  { atomicNumber: 98, symbol: 'Cf', name: 'Californium', persianName: 'کالیفرنیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f¹⁰ 7s²', group: 12, period: 7, atomicMass: 251 },
  { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', persianName: 'انیشتینیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f¹¹ 7s²', group: 13, period: 7, atomicMass: 252 },
  { atomicNumber: 100, symbol: 'Fm', name: 'Fermium', persianName: 'فرمیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f¹² 7s²', group: 14, period: 7, atomicMass: 257 },
  { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', persianName: 'مندلیفیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f¹³ 7s²', group: 15, period: 7, atomicMass: 258 },
  { atomicNumber: 102, symbol: 'No', name: 'Nobelium', persianName: 'نوبلیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f¹⁴ 7s²', group: 16, period: 7, atomicMass: 259 },
  { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', persianName: 'لورنسیم', category: ElementCategory.ACTINIDE, electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹', group: 17, period: 7, atomicMass: 262 },
  { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', persianName: 'رادرفوردیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', group: 4, period: 7, atomicMass: 267 },
  { atomicNumber: 105, symbol: 'Db', name: 'Dubnium', persianName: 'دوبنیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', group: 5, period: 7, atomicMass: 268 },
  { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', persianName: 'سیبورگیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', group: 6, period: 7, atomicMass: 269 },
  { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', persianName: 'بوهریم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', group: 7, period: 7, atomicMass: 270 },
  { atomicNumber: 108, symbol: 'Hs', name: 'Hassium', persianName: 'هاسیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', group: 8, period: 7, atomicMass: 269 },
  { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', persianName: 'مایتنریم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', group: 9, period: 7, atomicMass: 278 },
  { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', persianName: 'دارمشتادیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²', group: 10, period: 7, atomicMass: 281 },
  { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', persianName: 'رونتگنیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²', group: 11, period: 7, atomicMass: 282 },
  { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', persianName: 'کوپرنیسیم', category: ElementCategory.TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', group: 12, period: 7, atomicMass: 285 },
  { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', persianName: 'نیهونیم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', group: 13, period: 7, atomicMass: 286 },
  { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', persianName: 'فلروویم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', group: 14, period: 7, atomicMass: 289 },
  { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', persianName: 'مسکوویم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', group: 15, period: 7, atomicMass: 290 },
  { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', persianName: 'لیورموریم', category: ElementCategory.POST_TRANSITION_METAL, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', group: 16, period: 7, atomicMass: 293 },
  { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', persianName: 'تنسین', category: ElementCategory.HALOGEN, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', group: 17, period: 7, atomicMass: 294 },
  { atomicNumber: 118, symbol: 'Og', name: 'Oganesson', persianName: 'اوگانسون', category: ElementCategory.NOBLE_GAS, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', group: 18, period: 7, atomicMass: 294 },
];
